

Problem - 1: Array Creation:
1. Initialize an empty array with size 2X2.

In [1]:
import numpy as np

arr = np.zeros((2, 2))
arr

array([[0., 0.],
       [0., 0.]])

2. Initialize an all one array with size 4X2.

In [2]:
arr= np.zeros((4,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [3]:
arr = np.full((2, 2), 7)
arr

array([[7, 7],
       [7, 7]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [10]:
a = np.array([[1, 2],
              [3, 4]])
arr = np.zeros_like(a)
arr

array([[0, 0],
       [0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [11]:
a= np.array(([3,6],
             [2,5]))
arr=np.ones_like(a)
arr

array([[1, 1],
       [1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [12]:
new_list=[1,2,3,4]
arr=np.array(new_list)
arr

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [16]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [21]:
arr=np.arange(0,9)
arr=np.reshape(arr,(3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [22]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [23]:
arr=np.random.random(30)
arr=arr.mean()
arr

np.float64(0.4965327433572472)

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [29]:
arr = np.random.random((10, 10))
min_value = arr.min()
max_value = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Array:
 [[0.62892588 0.40465204 0.13756744 0.02522293 0.90881226 0.02550058
  0.40833331 0.1764247  0.81546779 0.1896244 ]
 [0.3970458  0.32989526 0.12921495 0.7179183  0.01033024 0.22365125
  0.73946483 0.08564061 0.4081949  0.85664786]
 [0.42333489 0.76390019 0.76372436 0.54808733 0.45382315 0.31929695
  0.98124274 0.36035245 0.54683613 0.26251407]
 [0.48490553 0.03816468 0.64259738 0.67098783 0.26052547 0.81838362
  0.36815051 0.39252808 0.94409368 0.65002398]
 [0.49099461 0.28872626 0.66940028 0.16328298 0.10332889 0.03984562
  0.90020355 0.50680441 0.67649615 0.71244809]
 [0.55618146 0.9133172  0.97400383 0.52876834 0.78600682 0.35217667
  0.65978669 0.40853479 0.93374282 0.48047719]
 [0.92664165 0.92498098 0.66140677 0.66160663 0.69083252 0.95621275
  0.97946071 0.43057662 0.36491691 0.13008431]
 [0.37072426 0.92127741 0.79057313 0.79601138 0.51227351 0.48226433
  0.50467729 0.20456373 0.58072132 0.67876995]
 [0.46002697 0.57361497 0.04656987 0.37435508 0.09715734 0.41546068
  0.

6. Create a zero array of size 10 and replace 5th element with 1.

In [31]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [32]:
arr=np.array([1,2,0,0,4,0])
reverse_arr=arr[::-1]
print(reverse_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [34]:
rows, cols = 5, 5
arr = np.zeros((rows, cols), dtype=int)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [35]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
WE have

In [36]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

1. Add the two array.

In [38]:
x_plus_y = x + y
v_plus_w = v + w

print("x + y:\n", x_plus_y)
print("v + w:\n", v_plus_w)

x + y:
 [[ 6  8]
 [10 13]]
v + w:
 [20 22]


2. Subtract the two array.

In [39]:
x_minus_y = x - y
v_minus_w = v - w

print("x - y:\n", x_minus_y)
print("v - w:\n", v_minus_w)

x - y:
 [[-4 -4]
 [-4 -3]]
v - w:
 [-2 -2]


3. Multiply the array with any integers of your choice.

In [40]:
x_multiply_y = x * y
v_multiply_w = v * w

print("x * y:\n", x_multiply_y)
print("v * w:\n", v_multiply_w)

x * y:
 [[ 5 12]
 [21 40]]
v * w:
 [ 99 120]


4. Find the square of each element of the array.

In [41]:
x_squared = x**2
v_squared = v**2

print("x squared:\n", x_squared)
print("v squared:\n", v_squared)

x squared:
 [[ 1  4]
 [ 9 25]]
v squared:
 [ 81 100]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [44]:
dot_v_w = np.dot(v, w)
print("Dot product of v and w:", dot_v_w)


dot_x_v = np.dot(x, v)
print("Dot product of x and v:", dot_x_v)


dot_x_y = np.dot(x, y)
print("Dot product of x and y:", dot_x_y)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [45]:
concat_x_y_rows = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_x_y_rows)


v_col = v.reshape(-1,1)
w_col = w.reshape(-1,1)
concat_v_w_cols = np.concatenate((v_col, w_col), axis=1)
print("Concatenate v and w along columns:\n", concat_v_w_cols)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get

In [47]:
try:
    concat_x_v = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error:\n", e)

Error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:


• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:




In [48]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

1. Prove A.A−1 = I.

In [51]:
I = np.dot(A, A_inv)
I_rounded = np.round(I, decimals=10)
print("A * A^-1 (rounded) =\n", I_rounded)

A * A^-1 (rounded) =
 [[1. 0.]
 [0. 1.]]


2. Prove AB ̸= BA.

In [52]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA? ", np.allclose(AB, BA))

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA?  False


3. Prove (AB)T = BTAT

In [54]:
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print( np.allclose(AB_T, BT_AT))

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [61]:
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([[-1],
                 [-3],
                 [9]])


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [62]:

X = np.dot(np.linalg.inv(A_eq), B_eq)
X = np.round(X, 5)
print("Solution [x, y, z] =\n", X)

Solution [x, y, z] =
 [[ 2.]
 [ 1.]
 [-2.]]
