

Problem - 1: Array Creation:
1. Initialize an empty array with size 2X2.

In [5]:
import numpy as np

arr = np.zeros((2, 2))
arr

array([[0., 0.],
       [0., 0.]])

2. Initialize an all one array with size 4X2.

In [6]:
arr= np.zeros((4,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [7]:
arr = np.full((2, 2), 7)
arr

array([[7, 7],
       [7, 7]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [8]:
a = np.array([[1, 2],
              [3, 4]])
arr = np.zeros_like(a)
arr

array([[0, 0],
       [0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [9]:
a= np.array(([3,6],
             [2,5]))
arr=np.ones_like(a)
arr

array([[1, 1],
       [1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [10]:
new_list=[1,2,3,4]
arr=np.array(new_list)
arr

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [11]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [12]:
arr=np.arange(0,9)
arr=np.reshape(arr,(3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [13]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [14]:
arr=np.random.random(30)
arr=arr.mean()
arr

np.float64(0.42708208590511687)

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [15]:
arr = np.random.random((10, 10))
min_value = arr.min()
max_value = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Array:
 [[0.89382143 0.72879407 0.51068356 0.22456508 0.41379977 0.06302277
  0.81417651 0.96327868 0.52629618 0.20891293]
 [0.0302311  0.81802802 0.25564748 0.89547816 0.76337006 0.66001504
  0.73079451 0.52471833 0.42695776 0.01600897]
 [0.26400381 0.09219047 0.54913888 0.76753217 0.70043443 0.37145916
  0.42825841 0.0442496  0.30708957 0.25308268]
 [0.78125883 0.22230498 0.31732303 0.24715418 0.0073664  0.59924956
  0.37553819 0.01850485 0.1198638  0.85473588]
 [0.53183745 0.04832865 0.22783916 0.1052048  0.1775163  0.21066564
  0.18007794 0.96357794 0.98109371 0.32206386]
 [0.82576511 0.90852385 0.69991054 0.15829441 0.3297319  0.0483053
  0.10544452 0.75259529 0.98258952 0.84479545]
 [0.1799668  0.86267938 0.09525452 0.36039206 0.13896229 0.26252925
  0.48757806 0.66550572 0.01081347 0.747619  ]
 [0.54072982 0.75312072 0.67763547 0.26551042 0.11203673 0.30523317
  0.54069196 0.40822589 0.77660397 0.68609455]
 [0.65102141 0.45977827 0.45748245 0.75152693 0.96016147 0.08473907
  0.6

6. Create a zero array of size 10 and replace 5th element with 1.

In [16]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [17]:
arr=np.array([1,2,0,0,4,0])
reverse_arr=arr[::-1]
print(reverse_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [18]:
rows, cols = 5, 5
arr = np.zeros((rows, cols), dtype=int)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [19]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
WE have

In [20]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

1. Add the two array.

In [21]:
x_plus_y = x + y
v_plus_w = v + w

print("x + y:\n", x_plus_y)
print("v + w:\n", v_plus_w)

x + y:
 [[ 6  8]
 [10 13]]
v + w:
 [20 22]


2. Subtract the two array.

In [22]:
x_minus_y = x - y
v_minus_w = v - w

print("x - y:\n", x_minus_y)
print("v - w:\n", v_minus_w)

x - y:
 [[-4 -4]
 [-4 -3]]
v - w:
 [-2 -2]


3. Multiply the array with any integers of your choice.

In [23]:
x_multiply_y = x * y
v_multiply_w = v * w

print("x * y:\n", x_multiply_y)
print("v * w:\n", v_multiply_w)

x * y:
 [[ 5 12]
 [21 40]]
v * w:
 [ 99 120]


4. Find the square of each element of the array.

In [24]:
x_squared = x**2
v_squared = v**2

print("x squared:\n", x_squared)
print("v squared:\n", v_squared)

x squared:
 [[ 1  4]
 [ 9 25]]
v squared:
 [ 81 100]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [25]:
dot_v_w = np.dot(v, w)
print("Dot product of v and w:", dot_v_w)


dot_x_v = np.dot(x, v)
print("Dot product of x and v:", dot_x_v)


dot_x_y = np.dot(x, y)
print("Dot product of x and y:", dot_x_y)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [26]:
concat_x_y_rows = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_x_y_rows)


v_col = v.reshape(-1,1)
w_col = w.reshape(-1,1)
concat_v_w_cols = np.concatenate((v_col, w_col), axis=1)
print("Concatenate v and w along columns:\n", concat_v_w_cols)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get

In [27]:

np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:


• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:




In [28]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

1. Prove A.A−1 = I.

In [30]:
I = np.dot(A, A_inv)
I_rounded = np.round(I, decimals=10)
print("A * A^-1 (rounded) =\n", I_rounded)

NameError: name 'A_inv' is not defined

2. Prove AB ̸= BA.

In [31]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA? ", np.allclose(AB, BA))

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA?  False


3. Prove (AB)T = BTAT

In [32]:
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print( np.allclose(AB_T, BT_AT))

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [33]:
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([[-1],
                 [-3],
                 [9]])


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [34]:

X = np.dot(np.linalg.inv(A_eq), B_eq)
X = np.round(X, 5)
print("Solution [x, y, z] =\n", X)

Solution [x, y, z] =
 [[ 2.]
 [ 1.]
 [-2.]]


4.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:


In [35]:
import time
import numpy as np



n = 1_000_000
mat_size = 1000



• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [36]:
a = list(range(n))
b = list(range(n))

start = time.time()
c = list(map(lambda x, y: x + y, a, b))
end = time.time()
print("List addition:", end - start, "seconds")

List addition: 0.05827927589416504 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [37]:
A = np.arange(n)
B = np.arange(n)

start = time.time()
C = A + B
end = time.time()

print("NumPy addition:", end - start, "seconds")

NumPy addition: 0.002392292022705078 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

In [38]:
start = time.time()
d = [x * y for x, y in zip(a, b)]
end = time.time()
print("List multiplication:", end - start, "seconds")

List multiplication: 0.04721498489379883 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [39]:
start = time.time()
D = A * B
end = time.time()
print("NumPy multiplication:", end - start, "seconds")

NumPy multiplication: 0.0028312206268310547 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [40]:
start = time.time()
dot1 = sum(x * y for x, y in zip(a, b))
end = time.time()
print("List dot product:", end - start, "seconds")

List dot product: 0.060137271881103516 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [41]:
start = time.time()
dot2 = np.dot(A, B)
end = time.time()
print("NumPy dot product:", end - start, "seconds")

NumPy dot product: 0.0017087459564208984 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

In [43]:
M1 = [[i + j for j in range(mat_size)] for i in range(mat_size)]
M2 = [[i + j for j in range(mat_size)] for i in range(mat_size)]

start = time.time()
result = [[sum(M1[i][k] * M2[k][j] for k in range(mat_size)) for j in range(mat_size)]
          for i in range(mat_size)]
end = time.time()
print("List matrix multiplication:", end - start, "seconds")

List matrix multiplication: 116.45970845222473 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [44]:
N1 = np.arange(mat_size**2).reshape(mat_size, mat_size)
N2 = np.arange(mat_size**2).reshape(mat_size, mat_size)

start = time.time()
np_result = N1 @ N2
end = time.time()
print("NumPy matrix multiplication:", end - start, "seconds")


NumPy matrix multiplication: 0.8249127864837646 seconds
